# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lUkAK15H_Cd1w_PMBtJntk1bbLKaWxLC
"""

# Simple Python Calculator
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: ")) #user inputs two numbers

operation = input("Choose operation (+, -, *, /): ")#user chooses operation

if operation == '+':
    print("Result:", num1 + num2)
elif operation == '-':
    print("Result:", num1 - num2)
elif operation == '*':
    print("Result:", num1 * num2)
elif operation == '/':
    if num2 != 0:
        print("Result:", num1 / num2)
    else:
        print("Cannot divide by zero")
else:
    print("Invalid operation")